### PR TITLE
Add support for recursive @imports

### LINKED ISSUE #2: Recursive @imports
At the current time, postcss-import-url only inlines the top-level `@imports`. For example, given these files:

**my.css**

```
@import url("https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/lumen/bootstrap.min.css");
// My custom css:
...
```

**https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/lumen/bootstrap.min.css**

```
@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic");/*!
 * bootswatch v3.3.6
 * Homepage: http://bootswatch.com
 * Copyright 2012-2015 Thomas Park
 * Licensed under MIT
 * Based on Bootstrap
*/
...
```

**https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic**

```
/* vietnamese */
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 300;
  src: local('Source Sans Pro Light'), local('SourceSansPro-Light'), url(https://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGD_j0nMiB9fPhg_k1wdK2h0.woff2) format('woff2');
  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
}
...
```

I would expect the following output:

```
/* vietnamese */
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 300;
  src: local('Source Sans Pro Light'), local('SourceSansPro-Light'), url(https://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGD_j0nMiB9fPhg_k1wdK2h0.woff2) format('woff2');
  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
}
...
/*!
 * bootswatch v3.3.6
 * Homepage: http://bootswatch.com
 * Copyright 2012-2015 Thomas Park
 * Licensed under MIT
 * Based on Bootstrap
*/
...
// My custom css:
...
```

Instead I get this:

```
@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic");/*!
 * bootswatch v3.3.6
 * Homepage: http://bootswatch.com
 * Copyright 2012-2015 Thomas Park
 * Licensed under MIT
 * Based on Bootstrap
*/
...
// My custom css:
...
```

Changing the default functionality would be a breaking change.

It's up to you weather you want to change the default behavior or just add a `recurse` option.

I might be able to submit a PR.

### PR DESCRIPTION
**Pull request by RyanZim**
Fixes #2.

Sorry if the code is a bit clumsy, I'm not too good at promises.

This should probably be tested, but I'm not sure how. One way would be to commit files into git and use http://rawgit.com/ to serve them as URLs. Thoughts?

GitHub wouldn't let me reopen #3, sorry.

### CODE REVIEW

**Comment by RyanZim** [comment]
@unlight ping?

**Comment by unlight** [comment]
@RyanZim 
Hi. Is this PR ready? I thought you are still working on something, sorry for delay.
Seems that you do not include unit tests for new functionality.
Let me review the code and write some tests.

**Comment by RyanZim** [comment]
I said:

> This should probably be tested, but I'm not sure how. ... Thoughts?

**Comment by unlight** [comment]
I've written [some tests](https://github.com/unlight/postcss-import-url/blob/97fc822d46168e351eb3dd28e399b86a28213450/test/test.js#L130) for recursive import feature. 
And unfortunately your PR did not pass. 
Looks like it's some kind of infinite loop/stack-overflow exception.

```
<--- Last few GCs --->
   60786 ms: Scavenge 683.2 (715.7) -> 683.2 (715.7) MB, 47.0 / 0 ms [allocation failure].
   60817 ms: Scavenge 683.2 (715.7) -> 683.2 (715.7) MB, 31.0 / 0 ms [allocation failure].
   60864 ms: Scavenge 683.2 (715.7) -> 683.2 (715.7) MB, 47.0 / 0 ms [allocation failure].
   60896 ms: Scavenge 683.2 (715.7) -> 683.2 (715.7) MB, 32.0 / 0 ms [allocation failure].
   60942 ms: Scavenge 683.2 (715.7) -> 683.2 (715.7) MB, 46.0 / 0 ms [allocation failure].
<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: Scavenger: semi-space copy
 Allocation failed - process out of memory
```

Not to worry though, I implemented feature by myself. I will release new major version soon.
Some things to discuss:
1. Why `recurse` instead of `recursive`?
2. What should we do with cyclic `@import` statements?

**Comment by RyanZim** [comment]
> 1. Why `recurse` instead of `recursive`?

Just quoting https://github.com/unlight/postcss-import-url/issues/2#issuecomment-229790999.

> 1. What should we do with cyclic `@import` statements?

It's up to you.

**Pull request closed without merging**
