### PR TITLE
feat: Support imports into `@layer`

### PR DESCRIPTION
**Pull request by argyleink**
adds a basic test, demonstrates basic feature. thoughts?

### CODE REVIEW

**Comment by unlight** [comment]
Thank you very much for pull request

This is CSS5 spec 😮 
Just checked mdn

Some cases are not covered by tests

```
@import url layer;
@import url layer(layer-name); // has test
@import url layer(layer-name) list-of-media-queries;
@import url layer(layer-name) supports(supports-query) list-of-media-queries;
```

It looks ok to me. I'll take a look again tomorrow (will do merge).

**Comment by argyleink** [comment]
yes, it's definitely got a little bit more work required to support the full spec 👍🏻  
thanks for taking a look! let me know how to help more. 

todo:
- [x] anonymous layer support
- [x] `@supports` query support

`@import url layer(layer-name) list-of-media-queries;` doesnt have a test but it should pass when created, here I'll go make one 🙂

**Comment by argyleink** [comment]
added a couple tests, looks like it just needs taught `@supports`

**Comment by argyleink** [comment]
added a failing test for us to work against

**Comment by argyleink** [comment]
i couldnt help it, wrapped up the rest of the features. i think we have good test coverage and the basic feature working. could use some code cleanup tho:
1. the nested tertiary is ugly
2. the parsing of whats inside the layer and supports `()` is ugly

**Pull request merged**
